### PR TITLE
test(contract): setup and init some tests for marmottoshis contract

### PR DESCRIPTION
**Pull request by balibou**

### CODE REVIEW

**Comment by balibou** [comment]
No need ?

**Comment by 0xNekr** [comment]
This is really great, but we want to keep only the contract and not all the confs/tests files in this directory! 

Thanks for the initiative, I will play the tests on my environment!

**Comment by balibou** [comment]
Oh no worries @0xNekr 👍

Always happy to help ! (especially for bug hunting, with a testing environment)
Also, while testing, I was a bit confused with the variable `_proof`. Maybe the naming is misleading.

**Comment by balibou** [comment]
I did some extra research for the proof, I got it, the variable is well named.

Possible improvement:
- creating a contract for verifying the proof ([like this one](https://github.com/OpenZeppelin/merkle-tree#validating-a-proof-in-solidity))

**Pull request closed without merging**
